<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>flo</string>
	</array>
	<key>foldingStartMarker</key>
	<string>^\s*(frame|framer|house)\s+([.a-zA-Z0-9_ &lt;]+)\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*\}|^\s*\]|^\s*\)|^\s*"""\s*$</string>
	<key>name</key>
	<string>FloScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(")</string>
			<key>end</key>
			<string>(")</string>
			<key>name</key>
			<string>string.quoted.double.floscript</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.floscript</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(to|by|with|from|per|for|cum|qua|via|as|at|in|of|on|re|is|if|be|into|and|not|\+|\-)\b</string>
			<key>name</key>
			<string>keyword.operator.floscript</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.floscript</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(#).*$\n?</string>
			<key>name</key>
			<string>comment.line.number-sign.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(frame|aux|framer|main|house)\b</string>
			<key>name</key>
			<string>entity.name.function.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(load|init|server|logger|log|loggee|first|over|under|next|done|timeout|repeat|native|benter|enter|recur|exit|precur|renter|rexit|print|put|inc|copy|set|rear|raze|go|let|do|bid|ready|start|stop|run|abort|use|flo|give|take)\b</string>
			<key>name</key>
			<string>storage.modifier.global.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>&lt;\=|&gt;  \=|\=\=|&lt;|&gt;|\!\=</string>
			<key>name</key>
			<string>keyword.operator.comparison.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(true|false)\b</string>
			<key>name</key>
			<string>constant.language.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(?i:)</string>
			<key>name</key>
			<string>constant.numeric.float.floscript</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b([1-9]+[0-9]*|0)</string>
			<key>name</key>
			<string>constant.numeric.integer.decimal.floscript</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.floscript</string>
	<key>uuid</key>
	<string>134e99bb-915a-463c-af1d-1182c95d009e</string>
</dict>
</plist>
